# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:

  # substitutions can be changed here if you are using this file directly in the ESPHome dashboard.  The better approach is
  # to incorporate this file as a package using the following lines, and then overwrite these substitutions in your local
  # yaml file by redefining them.
  #
  # packages:
  #   kauf.rgbww: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
  #

  name: kauf-espnow            # **** CHANGE DEVICE NAME TO SOMETHING UNIQUE PER DEVICE.  RENAME YAML FILE TO SAME NAME.    ****
                               # **** USE DASHES (-) INSTEAD OF SPACES OR UNDERSCORE (_).  USE ONLY LOWER CASE LETTERS.     ****

  enable_always:  "false"      # set to "true" to only utilize this when HASS is not connected

  # https://esphome.io/components/esphome.html#esphome-creators-project
  project_name: jv.kauf-espnow
  project_ver_num: "1.0"
  project_ver_let: a


external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote
esp_now:
wizmote:
  on_button:
    if:
      condition:
        # Check if remote matches
        - not:
            # If home assistant is down for some reason
            api.connected:
        - lambda: |-
            if (id(remote_mac) != format_hex(data.bssid, 6))
              return 0;

            // Check if sequence has changed (new button press)
            if (id(remote_sequence) == data.sequence)
              return 0;

            id(remote_sequence) = data.sequence;
            return 1;
      then:
        - if:
            condition:
              # Check if we're selecting a group
              - lambda: |-
                  if (data.button >= 16 && data.button <= 19) {
                    uint8_t actual = data.button - 15;
                    uint8_t i;
                    for (i=0; i < 4; i++){
                      if (id(remote_button)[i] == actual) {
                        id(remote_button_last_sel) = 1;
                        return 0;
                      }
                    }
                    // If we made it here, then there is no match
                    id(remote_button_last_sel) = 0;
                    return 0;
                  }
                  // If we're here, then this action is something other than select, and might apply to us
                  return id(remote_button_last_sel);
            then:
              - lambda: |-
                  if (data.button == 1) {
                    id (kauf_light).turn_on().perform();
                    // https://esphome.io/components/light/index.html#light-turn-on-action
                  } else if (data.button == 2) {
                    id (kauf_light).turn_off().perform();
                  } else if (data.button == 8) {
                    float brightness;
                    id(kauf_light).remote_values.as_brightness(&brightness);
                    brightness -= 0.1f;
                    if (brightness < 0.0f)
                      brightness = 0.0f;
                    id (kauf_light).turn_on().set_brightness(brightness).perform();
                  } else if (data.button == 9) {
                    float brightness;
                    id(kauf_light).remote_values.as_brightness(&brightness);
                    brightness += 0.1f;
                    if (brightness > 1.0f)
                      brightness = 1.0f;
                    id (kauf_light).turn_on().set_brightness(brightness).perform();
                  }
